### ISSUE TITLE
Move region check for chaos tests into chaos tests

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-chaos#126]
Chaos test only work on _new chaos_  region.

Currently, there is a test as part of the testbench processes that checks the region and skips chaos tests, if the region is wrong:
![image](https://user-images.githubusercontent.com/14032870/159714423-7bf3241c-7a22-4961-9fac-8cea881023a1.png)

As part of the refactoring, this check should be done inside the chaos test instead:

![image](https://user-images.githubusercontent.com/14032870/159714993-1aa2b767-74ab-4c52-8f5a-9870db747f14.png)

**Comment by Zelldon** [comment]
Current idea: Add a serviceTask which verifies the permissions in the cluster. If no permission return false and the experiemts are skipped. This allows to not depend anymore on the ultrachaos cluster, but more on the permission we have.

**Comment by Zelldon** [comment]
I don't want to have this check in the chaos models.
