### ISSUE TITLE
Scripts not resilient to gateway restarts

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe-chaos#136]
Here the script finds one gateway
https://github.com/zeebe-io/zeebe-chaos/blob/aee26dc8070b93e31a37d14798504149bc867498/chaos-workers/chaos-experiments/scripts/start-instance-on-partition-with-version.sh#L19

And then it tries to exec into the gateway
https://github.com/zeebe-io/zeebe-chaos/blob/aee26dc8070b93e31a37d14798504149bc867498/chaos-workers/chaos-experiments/scripts/start-instance-on-partition-with-version.sh#L31

But between execution of these two lines, the gateway pod was terminated and a new pod was started to replace it. But the script tried to access the terminated gateway and eventually timeouts, failing the experiment.

**Comment by Zelldon** [comment]
Might make sense to use the service to be more resilient. Or use the helper `retryUntilSuccess` as we do here https://github.com/zeebe-io/zeebe-chaos/blob/aee26dc8070b93e31a37d14798504149bc867498/chaos-workers/chaos-experiments/scripts/start-instance-on-partition-with-version.sh#L38

**Comment by deepthidevaki** [comment]
```
2022-04-21 04:34:21.442 CEST
chaos-worker
An instance where this happened:

"++ kubectl exec zeebe-gateway-c7fdf4f5c-v7mzz -n 0b25276f-1113-4627-9c17-5b867256e62a-zeebe -- zbctl create instance benchmark --insecure"
Debug
2022-04-21 04:34:21.505 CEST
chaos-worker
"error: cannot exec into a container in a completed pod; current phase is Failed"
```

The pod `zeebe-gateway-c7fdf4f5c-v7mzz ` was terminated before this time.

**Comment by deepthidevaki** [comment]
> Or use the helper `retryUntilSuccess` as we do here

It is already using `retryUntilSuccess`. The problem is it is retying to connect to the same terminated gateway.

**Comment by Zelldon** [comment]
Yeah because getGateway is not included in the loop.

**Comment by deepthidevaki** [comment]
Why don't we execute `zbctl` on the chaos worker? We have the authenticationDetails for the cluster available in the process.

**Comment by Zelldon** [comment]
Currently, it is independent of where and against what it is executed. Local, helm, cloud/saas etc.

**Comment by Zelldon** [comment]
I think it is no longer an issue, if we experience an issue the zbchaos worker will restart and retry later. Gateways are chosen random #297
