### ISSUE TITLE
Hypothesis: Loop process will not kill the Broker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-chaos#2]
### Hypothesis
We believe that a loop process will not kill the broker in any sense.

**Comment by Zelldon** [comment]
@korthout created one year ago :laughing: so maybe next time when you're medic we take a look at it?

**Comment by Zelldon** [comment]
addition to the Hypothesis: Will not kill the broker and we are still able to make progress on other process instances.

**Comment by korthout** [comment]
@Zelldon awesome! Let's do it!

**Comment by korthout** [comment]
Will it finally happen next week? 😲

**Comment by Zelldon** [comment]
We implemented logic to reject looping processes (at least most of them)
