### ISSUE TITLE
Automating with zbchaos fails with time outs on gateway during deploying processes

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-chaos#294]
After restructuring the zbchaos and running against our clusters, it often fails with timeout errors on deploying a process model.

This happened when automating with Testbench, running against SaaS, but also when executing locally and running against a self-managed cluster.

```
{"level":"debug","logging.googleapis.com/labels":{"clusterId":"","jobKey":"2251799813688688","processInstanceKey":"2251799813688668","title":"CPU stress on an Broker"},"logging.googleapis.com/operation":{"id":"2251799813688688"},"time":"2022-12-10T14:18:30.854571594+01:00","message":"Port forward to zell-chaos-zeebe-gateway-7796d8579f-pdttw"}
{"level":"debug","logging.googleapis.com/labels":{"clusterId":"","jobKey":"2251799813688688","processInstanceKey":"2251799813688668","title":"CPU stress on an Broker"},"logging.googleapis.com/operation":{"id":"2251799813688688"},"time":"2022-12-10T14:18:30.955492888+01:00","message":"Successfully created port forwarding tunnel"}
{"level":"debug","logging.googleapis.com/labels":{"clusterId":"","jobKey":"2251799813688688","processInstanceKey":"2251799813688668","title":"CPU stress on an Broker"},"logging.googleapis.com/operation":{"id":"2251799813688688"},"time":"2022-12-10T14:18:30.955897778+01:00","message":"Deploy file bpmn/one_task.bpmn (size: 2526 bytes)."}
panic: rpc error: code = DeadlineExceeded desc = Time out between gateway and broker: Request ProtocolRequest{id=3029, subject=command-api-1, sender=10.0.5.86:26502, payload=byte[]{length=2675, hash=1668380772}} to zell-chaos-zeebe-0.zell-chaos-zeebe.zell-chaos.svc:26501 timed out in PT15S
```

Interesting is that when this happens with Testbench and the deployed zbchaos worker the worker retries every 5 minutes (after job timeout) and fails again until the experiment fails due to timeout. I was not able to deploy either by hand with zbctl, which is a bit suspicious to me. It looks like that there is an issue in the gateway or broker when running such experiments.

### Details

As mentioned above I have run the experiment locally, against an self-managed cluster and increased the log level (Zeebe Trace, Atomic Debug). 

When the experiment fail then we can see in the gateway, that the request is sent to the broker:

```

2022-12-10 14:18:30.940 CET
￼
zeebe-gateway
Send request 1519360045 to zell-chaos-zeebe-0.zell-chaos-zeebe.zell-chaos.svc:26501 with topic command-api-1
```

(At least I hope this is the request ?!)

In the broker I see several issues polling etc between leader and followers and later having different leaders.

```
2 - Failed to probe Member{id=0e1d070c-36bb-4023-8b6c-706186e68289, address=zell-chaos-zeebe-0.zell-chaos-zeebe.zell-chaos.svc:26502, properties={}, version=null, timestamp=0, state=null, incarnationNumber=0}
```

Furthermore I see that an response can't be sent back (from broker 0, which is our leader at this time):

```
2022-12-10 14:18:30.654 CET

zell-chaos-zeebe-0

zeebe
Received a reply for message id:[2134] but was unable to locate the request handle
```

**Comment by npepinpe** [comment]
Did we try checking network traffic with Wireshark/tshark?

**Comment by Zelldon** [comment]
What we (@npepinpe and I ) did so far:

* We discussed the potential error cases
  * @npepinpe made a point about whether it is written to the log
  * I checked it with zdb, the deploy command, which failed, was not on the log 
[output.json.txt](https://github.com/zeebe-io/zeebe-chaos/files/10206011/output.json.txt)
  * We discussed whether dispatcher might not write the commands, @npepinpe remembers there is a weird behavior in CommandAPI https://github.com/camunda/zeebe/blob/main/broker/src/main/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiRequestHandler.java#L115 If the command is not written, it is silently ignored...
  * I added a new log statement and build a docker image to run the experiments again
  * to be continued...

**Comment by npepinpe** [comment]
I'm surprised we've never had issues with this in prod, where the gateway fails to contact certain brokers because of this :thinking:

**Comment by Zelldon** [comment]
I have run the experiment again and checked the whether DNS resolving is an issue:

```
$ k exec -it zeebe-gateway-6d79bf8db4-56bkl -- zbctl --insecure status
Defaulted container "zeebe-gateway" out of: zeebe-gateway, debugger-ghlwh (ephem)
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 8.1.5
Brokers:
  Broker 0 - zeebe-0.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local:26501
    Version: 8.1.5
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 1 - zeebe-1.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local:26501
    Version: 8.1.5
    Partition 1 : Leader, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 2 - zeebe-2.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local:26501
    Version: 8.1.5
    Partition 1 : Follower, Healthy
    Partition 2 : Leader, Healthy
    Partition 3 : Leader, Healthy

```

Deployment fails again, so we have to check whether we can resolve leader for partition one, which is Broker 1. In the experiment, we port-forwarded to `Port forward to zeebe-gateway-6d79bf8db4-56bkl`

```
$ kubectl debug -it --image=registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3 --target=zeebe-gateway zeebe-gateway-6d79bf8db4-56bkl
Targeting container "zeebe-gateway". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-ghlwh.
If you don't see a command prompt, try pressing enter.
root@zeebe-gateway-6d79bf8db4-56bkl:/# 
root@zeebe-gateway-6d79bf8db4-56bkl:/# nslookup zeebe-1.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local
Server:		10.0.48.10
Address:	10.0.48.10#53

Name:	zeebe-1.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local
Address: 10.56.22.117
```

Also from the pod status, we can see the same IP:

```
$ k get pod zeebe-1 -o jsonpath="{.status.podIP}"
10.56.22.117
```

In order to verify the state of the gateway I did a heap dump:

```
$ kubectl debug -it -c debugger --image=eclipse-temurin:17-jdk-focal --target=zeebe-gateway zeebe-gateway-6d79bf8db4-56bkl -- /bin/bash
Targeting container "zeebe-gateway". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
If you don't see a command prompt, try pressing enter.
root@zeebe-gateway-6d79bf8db4-56bkl:/# jps
7 StandaloneGateway
621 Jps
root@zeebe-gateway-6d79bf8db4-56bkl:/# jmap -dump:live,format=b,file=/usr/local/zeebe/data/heap.dump 7
Dumping heap to /usr/local/zeebe/data/heap.dump ...
Heap dump file created [43820610 bytes in 1.222 secs]
```

Copying the heap dump
```
$ k cp zeebe-gateway-6d79bf8db4-56bkl:/usr/local/zeebe/data/heap.dump ./heap.dump
Defaulted container "zeebe-gateway" out of: zeebe-gateway, debugger-ghlwh (ephem), debugger (ephem)
tar: Removing leading `/' from member names
[cqjawa debug/ cluster: ultrachaos ns:967418c4-dd62-4230-939b-0597897d8685-zeebe]$ ls -la
total 42804
drwxr-xr-x  2 cqjawa cqjawa     4096 Dec 14 16:02 .
drwx------ 34 cqjawa cqjawa     4096 Dec 14 16:01 ..
-rw-r--r--  1 cqjawa cqjawa 43820610 Dec 14 16:02 heap.dump
```

Checking the heap dump we see that there still some old IP's be used, and there is also already the new one available it seems, 10.56.22.117 vs 10.56.22.116 (old, multiple objects)
![inet](https://user-images.githubusercontent.com/2758593/207631461-c17ac04f-895b-472b-949a-183621a5cd6e.png)

**Comment by deepthidevaki** [comment]
A similar issue https://github.com/camunda/zeebe/issues/8264 which @oleschoenburg mentioned in the slack.

**Comment by Zelldon** [comment]
## Investigation: 

What I found out so far, is that it looks like we have two separate issues.

One is that our infrastructure has some issues with setup pods via calico (?) I have observed during executing some experiments that a Broker was not able to come up, because it had no `eth0` interface configured. It was not able to reach any other node, which means also no DNS resolution was possible.

Secondly, we have the issue with the gateways described above not being able to resolve the correct IP. I have investigated this further as well.

### Details: Broker doesn't come up

When running some experiments against my cluster, which looked healthy before it failed because one pod didn't come up and it looked like it can't reach the others, so I did the same checks.

```sh
$ kubectl debug -it --image=registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3 --target=zeebe zeebe-2
Targeting container "zeebe". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-jb6mn.
If you don't see a command prompt, try pressing enter.
root@zeebe-2:/# 
root@zeebe-2:/# nslookup zeebe-0.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local:26501
;; connection timed out; no servers could be reached

root@zeebe-2:/# nslook up zeebe-1.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local      
bash: nslook: command not found
root@zeebe-2:/# nslookup zeebe-1.zeebe-broker-service.967418c4-dd62-4230-939b-0597897d8685-zeebe.svc.cluster.local
;; connection timed out; no servers could be reached
```

I checked whether the nameserver is reachable
```
$ kubectl get svc --namespace=kube-system
NAME                            TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                        AGE
calico-typha                    ClusterIP   10.0.63.197   <none>        5473/TCP                       198d
default-http-backend            NodePort    10.0.49.249   <none>        80:30937/TCP                   224d
kube-dns                        ClusterIP   10.0.48.10    <none>        53/UDP,53/TCP                  2y132d
```
It was not:

```
root@zeebe-2:/# ping -c 3 10.0.48.10
connect: Network is unreachable
```

When checking the network interfaces, I saw that `eth0` was not set up.

```
oot@zeebe-2:/# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

SRE was able to fix this by, restarting the calico nodes. Still, it is unclear why this happened. If we see that again we should ping SRE.

### Details: Gateway can't talk with brokers

After the issue from above was resolved I run again our experiments against the cluster. This time I saw again the gateway issues, that it can't talk with the other brokers. The client was not able to deploy any processes.


I took again a heap dump and checked whether I can resolve the addresses on the pod. Name resolving was in general possible, but the gateway had still old IP's in the heap.

![newips](https://user-images.githubusercontent.com/2758593/207874875-c09c019f-21ff-4616-ac92-e74032dea209.png)
![gw-use-old-ips](https://user-images.githubusercontent.com/2758593/207874880-212cc9cd-7e37-433d-b528-502e3a3be26f.png)

I have investigated a bit further how the DNS TTL works in Java and checked our code a bit regarding this issue.

If found several resources, like https://stackoverflow.com/questions/1256556/how-to-make-java-honor-the-dns-caching-timeout which point out that you can configure DNS TTL, if you want but if not set it should be around 30 seconds.

I was able to prove that based on the code and heap dump as well.

Taking a look at how the addresses are cached in InetAddress and how the expiry is calculated we can see the following:

![defaultCachePolicy](https://user-images.githubusercontent.com/2758593/207875238-cceaa2b2-c691-4c10-8b9c-506d654f617c.png)
![cachedAddresses](https://user-images.githubusercontent.com/2758593/207875244-175034f3-5b5f-445c-b629-dcd111efdc6e.png)

Furthermore, I was able to find the CachedAddresses in the heap dump I took earlier. 
![expiryaddresses](https://user-images.githubusercontent.com/2758593/207875455-7efe2fa5-ae64-4f9b-b90f-9a5de866c777.png) 

Since they use nanoseconds as expiry time, we can't just use the normal Unix timestamp to calculate the time. [We need to use the same reference as the System.nanoTime() used when creating the timestamp. ](https://www.educative.io/answers/what-is-the-systemnanotime-function-in-java) I checked for the ActorClock nanoseconds field to have a reference and to verify how far in the future this expiry would be.

![actorclockns](https://user-images.githubusercontent.com/2758593/207876094-081c7351-51fe-4e07-8071-eac30643d004.png)

As we can see based on the values is that the difference is ~12 seconds

![expiry12sec](https://user-images.githubusercontent.com/2758593/207876179-e66b17ec-e474-497a-bc5f-3b95e88a4a6a.png)

I have also further checked whether we reuse any IP or addresses, but we seem to generously create new Address objects anytime, and also try to resolve the addresses when connecting. 

### Details: Chaos Experiment changes

I tried to overcome the issue, by not always choosing the same leader. Previously in our experiments we often just used partition one leader, I thought this might be an issue to restart the node maybe too often. It is likely that the same node becomes leader again if it has the longes log :shrug: 

This didn't help, unfortunately.

## Current State - Next

I guess I need to dig a bit deeper. I have also improved our current toString from `Address` to print the resolved IP (which is quite useful in debugging/tracing such issues). I will rerun QA with a docker image of that version.

Right now I feel it is an infrastructure issue, and not a code issue, since we are also easy to reproduce it in SaaS (not sure whether in self-managed I ever saw it. Have to check again.)

**Comment by Zelldon** [comment]
* I wrote an runbook regarding the dns troubleshooting https://github.com/camunda-cloud/runbook/pull/154

I investigated further why addresses seem to be reused. I might be have an idea, it looks like that we open channels and reuse them for a longer period of time. Interesting is that we not close the channel on timeout, which might cause the issue which we currently see. I tried to fix it with https://github.com/camunda/zeebe/commit/2fcf80e56fac035ae3d8e44e23ba98406dbe978e

Unfortunatelty I doesn't resolve the issue yet, but I might have some more insights since I also added some more details for the logging as also described above.

What I was able to see is that:

When the deploy is sent: [https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22testbench-1-x-prod%22%0Alabels.k8s-pod%2Fapp%3D%22zbchaos-worker%22;pinnedLogId=2022-12-15T15:48:24.973815753Z%2Fgkx8qq66chfvwocy;cursorTimestamp=2022-12-15T15:48:39.997527202Z?project=zeebe-io](Deploy file bpmn/one_task.bpmn (size: 2526 bytes).)

We direct it to the zeebe-1 [https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22ef47e566-7c38-42d1-b815-91efbb7ff317-zeebe%22%0Aresource.labels.pod_name:%22zeebe-gateway-%22;timeRange=2022-12-15T14:57:24.136Z%2F2022-12-15T15:49:24.136Z;pinnedLogId=2022-12-15T15:48:24.988738619Z%2Ffc16t195qs1y17jm;cursorTimestamp=2022-12-15T15:48:25.214613789Z?project=camunda-cloud-240911](Send request 808630568 to zeebe-1.zeebe-broker-service.ef47e566-7c38-42d1-b815-91efbb7ff317-zeebe.svc.cluster.local/<unresolved>:26501 with topic command-api-1)

The request seem to fail later [https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22ef47e566-7c38-42d1-b815-91efbb7ff317-zeebe%22%0Aresource.labels.pod_name:%22zeebe-gateway-%22;timeRange=2022-12-15T14:57:24.136Z%2F2022-12-15T15:49:24.136Z;pinnedLogId=2022-12-15T15:48:39.989968991Z%2F5i3or0o86l9qzh03;cursorTimestamp=2022-12-15T15:48:40.341321460Z?project=camunda-cloud-240911](Request 808630568 failed, will not retry!)

We seem to resolve the correct address, see here [Activating server protocol version V2 for connection to /10.56.21.41:35654](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22ef47e566-7c38-42d1-b815-91efbb7ff317-zeebe%22%0Aresource.labels.pod_name:%22zeebe-gateway-%22;timeRange=2022-12-15T14:57:24.136Z%2F2022-12-15T15:49:24.136Z;pinnedLogId=2022-12-15T15:48:25.118008170Z%2Fs6aobsk41f0uea9h;cursorTimestamp=2022-12-15T15:48:25.214613789Z?project=camunda-cloud-240911)

But somehow the port is wrong ? @npepinpe do you know why this could happen ? Or is this not relevant?

We are also able to resolve the correct address here [https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22ef47e566-7c38-42d1-b815-91efbb7ff317-zeebe%22%0Aresource.labels.pod_name:%22zeebe-gateway-%22;timeRange=2022-12-15T14:57:24.136Z%2F2022-12-15T15:49:24.136Z;pinnedLogId=2022-12-15T15:48:25.196356206Z%2Fh86gqy8hcwqa1kk5;cursorTimestamp=2022-12-15T15:48:25.214613789Z?project=camunda-cloud-240911](Resolved Address zeebe-broker-service/10.56.21.41:26502 to bootstrap client.)

but somehow it doesn't work.

Would be happy for any input.

**Comment by Zelldon** [comment]
Just for posterity:

**Comment by Zelldon** [comment]
Yesterday I worked on adding some new metrics to the NettyMessagingService https://github.com/camunda/zeebe/tree/zell-zbchaos-investigation

I have rerun the chaos experiments and we can see clearly in the metrics that for quite a while it is sending requests to the wrong IP!

![request-gw](https://user-images.githubusercontent.com/2758593/208615208-1882721e-bbbb-49ae-a3af-220e968d0e05.png)


From 8:28 until 8:40 it is sending to `"10.56.25.48"` instead of `"10.56.25.49"`, when it is starting to the correct IP we see that the processing goes up again. It is interesting that the responses don't show an error, might be worth investigating this further.

[The calico node logs show that the IP was set up correctly at ~8:28 (please be aware of UTC timestamp):](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22kube-system%22%0Alabels.k8s-pod%2Fk8s-app%3D%22calico-node%22%0A%2210.56.25.49%22;pinnedLogId=2022-12-20T07:28:22.608979894Z%2F8k8g5xemmrv6mc2k;cursorTimestamp=2022-12-20T07:29:18.555964610Z?project=camunda-cloud-240911)

```
2022-12-20 07:28:22.605 [INFO][69] felix/int_dataplane.go 1585: Received *proto.IPSetDeltaUpdate update from calculation graph msg=id:"s:J1TO0ckqzlO41yn5_FpfVzhgxiDF2WNh8uCIpw" added_members:"10.56.25.49/32"
2022-12-20 07:28:22.608 [INFO][68] felix/int_dataplane.go 1585: Received *proto.WorkloadEndpointUpdate update from calculation graph msg=id:<orchestrator_id:"k8s" workload_id:"50ab3950-b7e2-4a53-8250-f7201f3196fe-zeebe/zeebe-1" endpoint_id:"eth0" > endpoint:<state:"active" name:"calie904863dde8" profile_ids:"kns.50ab3950-b7e2-4a53-8250-f7201f3196fe-zeebe" profile_ids:"ksa.50ab3950-b7e2-4a53-8250-f7201f3196fe-zeebe.default" ipv4_nets:"10.56.25.49/32" tiers:<name:"default" ingress_policies:"50ab3950-b7e2-4a53-8250-f7201f3196fe-zeebe/knp.default.zeebe-network-policy" > > 
```

[The kube-dns logs also doesn't show any issues. We only see the following entry when cluster is setup:](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22kube-system%22%0Alabels.k8s-pod%2Fk8s-app%3D%22kube-dns%22%0A;pinnedLogId=2022-12-20T07:22:08.511775807Z%2F42r2nqeshuy35sxj;cursorTimestamp=2022-12-20T07:22:08.554564665Z?project=camunda-cloud-240911)
```
Could not find endpoints for service "zeebe-broker-service" in namespace "50ab3950-b7e2-4a53-8250-f7201f3196fe-zeebe". DNS records will be created once endpoints show up.
```


\cc @npepinpe
