### ISSUE TITLE
Chaos: Disconnect zbchaos command fails with runtime error

### ISSUE THREAD

**Issue by shahamit** [zeebe-io/zeebe-chaos#331]
## Chaos Experiment
We tried the disconnect zbchaos command against a locally installed zeebe cluster (v - 8.1.6). The command fails with a runtime error `invalid memory address or nil pointer dereference`

Please find the screenshots attached with different flags. All of them lead to the same error. Kindly share some insights. Thanks.
![Screenshot from 2023-03-14 16-08-38](https://user-images.githubusercontent.com/1281926/225020376-478bb58b-9960-44e8-8fa4-e38d8d93089c.png)
![Screenshot from 2023-03-14 14-53-57](https://user-images.githubusercontent.com/1281926/225020408-35b912e2-f702-4919-810a-e9b334c3c7d1.png)

**Comment by Zelldon** [comment]
Hey @shahamit zbchaos doesn't support local installation. The expected setup is either deployment via helm-charts in kubernetes or internally setup in our SaaS.

**Comment by Zelldon** [comment]
I will try to document this better

**Comment by shahamit** [comment]
The local setup was done through helm on k8s. We updated the podaffinity
rules to null to install multiple gateways and brokers. Would that be a
problem too?

Thanks

**Comment by Zelldon** [comment]
Can you rerun the same with verbosity enabled?

**Comment by shahamit** [comment]
@Zelldon - there are a couple of blockers that we observed when executing the chaos tool against an under-load zeebe cluster. One of them is this issue and the other one is gateway termination logged [here](https://github.com/zeebe-io/zeebe-chaos/issues/336). 

There are more failures that we observed when executing the `restart gateway` chaos experiment but we thought of re-executing it once there is some analysis done on these logged ones. 

Should I move these issues on the zeebe repo to gain traction since anyways there are no issues with the experiment itself but its outcome?

Thanks

**Comment by Zelldon** [comment]
Hey @shahamit 

> Should I move these issues on the zeebe repo to gain traction since anyways there are no issues with the experiment itself but its outcome?

Sounds reasonable to me, but lets first collect a bit more information in https://github.com/zeebe-io/zeebe-chaos/issues/336
