### ISSUE TITLE
Failed test due to permission errors: Stress CPU on Broker

### ISSUE THREAD

**Issue by remcowesterhoud** [zeebe-io/zeebe-chaos#386]
## Description

Every day the test `Stess CPU on Broker` fails. It runs in a timeout when trying to apply the stress to the broker.

Stress is applied using the command `apt -qq update`. Due to recent permissions changes it is no longer allowed to execute this command. As a result the job never completes, the chaos is never introduced and the test runs into a 1 hour timeout.

**Comment by oleschoenburg** [comment]
Just a small correction, the `apt -qq update` command is run in preparation to installing the `stress` tool which takes care of producing CPU stress.

**Comment by remcowesterhoud** [comment]
Fixed with https://github.com/zeebe-io/zeebe-chaos/pull/388
