### ISSUE TITLE
Hypothesis: Data loss of one node will not cause cluster wide issues

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-chaos#4]
### Hypothesis
We believe that a data loss of one node, will not cause cluster wide issues. For example we could delete a PVC.

**Comment by Zelldon** [comment]
Thanks @deepthidevaki :+1:

**Comment by Zelldon** [comment]
Closed by #275 :rocket:

**Comment by deepthidevaki** [comment]
We only added experiment for Production - S. But I think that is enough.
