### ISSUE TITLE
Hypothesis: Broker scaling does not impact processing performance

### ISSUE THREAD

**Issue by oleschoenburg** [zeebe-io/zeebe-chaos#457]
### Hypothesis

While adding new brokers to a cluster, the processing performance (latency and throughput) remains stable.

**Comment by npepinpe** [comment]
Is this something we can assess with zbchaos? :thinking: It might be better as an E2E test.

**Comment by oleschoenburg** [comment]
Not automatically, as far as I know. But I can still compare metrics by hand to asses the impact.
