### ISSUE TITLE
Update zeebe-chaos for Zeebe 1.x compatibility

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe-chaos#53]
With camunda-cloud/zeebe#6455 we've renamed workflow to process. This means our chaos experiments for snapshot will fail, since we expect workflowInstanceKey etc as output from zbctl. 

This change is part of Zeebe 1.0.0, and zeebe-chaos should be compatible again.

Required for https://github.com/zeebe-io/zeebe-cluster-testbench/issues/248

**Comment by Zelldon** [comment]
fixed by https://github.com/zeebe-io/zeebe-chaos/pull/54
