### ISSUE TITLE
Deployment distribution test is flaky

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe-chaos#61]
After the network is disconnected between two brokers, sometimes the client connect to the gateway in one of the disconnected broker which then tries to send a command to the other broker. This fails and the client requests times out because the gateway never gets a reply from the disconnected broker. 

Not sure how to mitigate this in the test. We cannot control which broker client connects to.

**Comment by Zelldon** [comment]
Nice catch! Standalone Gateway would help here :sweat_smile:

**Comment by deepthidevaki** [comment]
:smile:  Yes. Standalone Gateway helps.

**Comment by deepthidevaki** [comment]
Another issue with this test - partial network partition triggers an election. So the leader's determined before the test are not necessarily the same during the test. When this happens, we are not really testing the scenario that we want to test.

**Comment by Zelldon** [comment]
We are not determining who is the leader :thinking: we just deploy to partition one afaik?

**Comment by deepthidevaki** [comment]
We are disconnecting leader of partition 1 and leader of partition 3. And then deploy to partition 1, reconnect and verifies if it is deployed in partition 3 by creating instances. But after the first disconnect it is possible that the leader of partition 3 and partition 1 changes. There is no guarantee that they are disconnected. It can be on the same node as well. So we are not really testing the network disconnection. Test doesn't fail because of this.

**Comment by Zelldon** [comment]
We only create a network disconnection if they are on other nodes otherwise we just do nothing https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-experiments/scripts/disconnect-leaders.sh

**Comment by Zelldon** [comment]
> Test doesn't fail because of this. 

I dont get it so what are we talking about then?

**Comment by deepthidevaki** [comment]
Expected scenario:
1. Leader of partition 1 = zeebe-1
2. Leader of partition 3 = zeebe-2
3. Disconnect zeebe-1 and zeebe-2
4. We deploy new version, replication to partition-3 fails because leaders are disconnected
5. Reconnect zeebe-1 and zeebe-2
6. Zeebe-1 should now replicate the new version to partition 3
7. The test verifies if deployment is distributed

What actually happens:
1. Leader of partition 1 = zeebe-1
2. Leader of partition 3 = zeebe-2
3. Disconnect zeebe-1 and zeebe-2
4. This can internally trigger an election - as result  Zeebe-1 is leader for partition 1 and partition 3 (this may not happens always)
5. We deploy new version, new version is immediately replicate to partition 3
6. Reconnect zeebe-1 and zeebe-2
7. Nothing much to do because deployment is already replicated
8. We verifies if deployment is distributed

So what I'm saying is the test may not be testing the actual scenario that we want to test. The test may not fail if there is a bug in deployment distribution that occur during network partition.

**Comment by Zelldon** [comment]
Thanks for sharing. Yeah, I mean this is fine we can't do much about it or can we? In the end the deployment should be distributed, which should also be in this case right? So why is the test failing ? :smile: 

> The test may not fail if there is a bug in deployment distribution that occur during network partition.

It will, since it is run regularly. The leader change doesn't happen always right?

Do you have an idea to improve this situation?

**Comment by deepthidevaki** [comment]
> So why is the test failing ?

See the issue description. That is the the reason the test is flaky.

> The leader change doesn't happen always right?

Don't know. It is highly likely that it happens. We might have to look at the logs of all successful runs. In all failed runs, I see this behavior. 

> Do you have an idea to improve this situation?

May be if we disconnect the partitions that doesn't share a replication group. It would be possible only in L cluster. We disconnect partition 1 and partition 4. Partition 1 members are 0,1,2. Partition 4 members are 3,4,5. So disconnecting the leaders doesn't trigger a leader change for partition 1 and 4.

**Comment by deepthidevaki** [comment]
>  So essentially we need the standalone gateway and run it with partition 1 and 4 to test it reliably.

Yes. This summarizes it pretty well.

**Comment by Zelldon** [comment]
Verified via https://zeebe-io.github.io/zeebe-chaos/2022/08/02/deployment-distribution/

And brought back to life via https://github.com/zeebe-io/zeebe-chaos/commit/eb0780dde5d111bf646f0a066784756bf64c93d3

Need to create a new release and afterwards reference that in test bench. As follow up I want to add DMN resources in our chaos worker.

**Comment by Zelldon** [comment]
Works now again https://camunda.slack.com/archives/CSQ2E3BT4/p1659521777373269?thread_ts=1659446100.254159&cid=CSQ2E3BT4
