### ISSUE TITLE
Reduce timeout for kubectl wait for readiness check

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe-chaos#94]
The [verify-readiness.sh](https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-workers/chaos-experiments/scripts/verify-readiness.sh) uses `kubectl wait` to wait for the pod to become ready. We've seen that this can hang sometimes. 

We should use Zeebe's job retry mechanism to retry the verify-readiness if it hangs. However, because the `--timeout` flag for that command is the same as the timeout used by the timer catch event. We should reduce the timeout passed to the wait command

**Comment by Zelldon** [comment]
we no longer have this
